# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EICDRNv6qAi3hbcYelgNzHiV-umwhIg-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path = "/content/drive/MyDrive/Births.csv"

birth = pd.read_csv(path)

birth.head(31)

birth['decade'] = 10 * (birth['year'] // 10)
birth.pivot_table(values='year', index='decade', columns='gender', aggfunc='sum')

birth_decade = birth.pivot_table(index='decade', columns='gender', aggfunc='sum')
birth_decade.plot()
plt.xlabel("Decade")
plt.ylabel("Births per Year")
plt.show()